# Generated by Django 4.2.18 on 2025-02-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_user_options_alter_user_managers_comment_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='default_password', max_length=128),
        ),
    ]
